# This file is auto-generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class Nit < Formula
  desc "Terminal-native AI agent orchestrator with TUI"
  homepage "https://nit.tools"
  version "0.1.1"
  license "MIT"

  # Single universal Mach-O covers Apple Silicon and Intel Macs.
  on_macos do
    url "https://download.nit.tools/v0.1.1/nit-v0.1.1-universal-apple-darwin.tar.gz"
    sha256 "8596629bf5224c953859eb4e2272f8026cc52b9e4cf07ae995c46f993dfaed6f"
  end

  on_linux do
    on_intel do
      url "https://download.nit.tools/v0.1.1/nit-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "770917cc908128ed1e0491608cdca4dce64a32e2055297307ea7adfbc2a8ed65"
    end
  end

  def install
    bin.install "nit"
    bin.install "nit-mcp-server"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nit --version 2>&1", 0)
  end
end
