# This file is auto-generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class Nit < Formula
  desc "Terminal-native AI agent orchestrator with TUI"
  homepage "https://nit.tools"
  version "0.2.7"
  license "MIT"

  # Single universal Mach-O covers Apple Silicon and Intel Macs.
  on_macos do
    url "https://download.nit.tools/v0.2.7/nit-v0.2.7-universal-apple-darwin.tar.gz"
    sha256 "6bf5554710686d25bc7abad2a5305f0d10d4e7c58769f697a2e11a268bdc637a"
  end

  on_linux do
    on_intel do
      url "https://download.nit.tools/v0.2.7/nit-v0.2.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "439d20bae90fc78f7826174fb3d4d2142f53adf473386230f2fd8589b4ccc695"
    end
  end

  def install
    bin.install "nit"
    bin.install "nit-mcp-server"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nit --version 2>&1", 0)
  end
end
