# This file is auto-generated by .github/workflows/release.yml.
# Do not edit by hand; changes will be overwritten on the next release.
class Nit < Formula
  desc "Terminal-native AI agent orchestrator with TUI"
  homepage "https://nit.tools"
  version "0.2.1"
  license "MIT"

  # Single universal Mach-O covers Apple Silicon and Intel Macs.
  on_macos do
    url "https://download.nit.tools/v0.2.1/nit-v0.2.1-universal-apple-darwin.tar.gz"
    sha256 "f6350670230213ba8594d97a88cc51ba34b90015736ba3b8e3f8a521aa37daa4"
  end

  on_linux do
    on_intel do
      url "https://download.nit.tools/v0.2.1/nit-v0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ce377406201afdab24fe8816501950b100a3be79791b7fdc2dc9533782eee76e"
    end
  end

  def install
    bin.install "nit"
    bin.install "nit-mcp-server"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nit --version 2>&1", 0)
  end
end
